name: Create Release Branch and PR

on:
  push:
    branches:
      - develop

jobs:
  create_pr:
    runs-on: ubuntu-latest
    env:
      # githubのコンソールから入力したリリース名を環境変数へ保存
      RELEASE_BRANCH_NAME: release/${{ github.event.inputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Create and push release branch
        run: |
          git switch release || git switch -c release
          git push origin release
      - run: gem install --no-document git-pr-release
      - name: Create PR for release
        run: git-pr-release
        env:
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_LABELS: release
          TZ: Asia/Tokyo
